### ISSUE TITLE
Bug: setting reviewers for multiple file patterns is not working properly 

### ISSUE THREAD

**Issue by yikeke** [shufo/auto-assign-reviewer-by-files#22]
Hi your action suits very well for my use case, so thanks for your work on this project.

I think I might bump into a bug today. Could you please provide some help? @shufo 

My action is:

```
name: "Auto Assign"
on:
  pull_request:
    branches:
      - master
    types: [opened]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-files@v1.0.0
      with:
        config: '.github/assign-by-files.yml'
        token: ${{ secrets.GITHUB_TOKEN }}
```

My `assign-by-files.yml` file is like:

```
---
'*.md':
  - AAA

'media/':
  - DDD

'.github/':
  - BBB
  - CCC
```

My PR changed 2 yml files under `.github/` folder so the bot should assign only BBB and CCC as reviewers. And the github action runs with no error but the bot requested AAA, BBB, CCC, DDD as reviewers. Could you please check on this?

**Comment by shufo** [comment]
@yikeke 
Thanks for reporting issue!
It seems bugs around minimatch and Fixed in [this](https://github.com/shufo/auto-assign-reviewer-by-files/pull/26) PR.
>Minimatcher was used incorrectly and was matching every rule

Could you try latest version that merged this PR? 

```yaml
name: "Auto Assign"
on:
  - pull_request

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-files@v1.1.1
      with:
        config: '.github/assign-by-files.yml'
        token: ${{ secrets.GITHUB_TOKEN }}
```
