### ISSUE TITLE
Error is thrown: Cannot read properties of undefined (reading 'number')

### ISSUE THREAD

**Issue by katyaaronov** [shufo/auto-assign-reviewer-by-files#292]
Hello,

The workflow seems to work well on feature branches, however it fails when a feature branch is merged (pushed) to the master branch with the following error:
`Cannot read properties of undefined (reading 'number')`

assign_reviewer.yml:

```
name: Assign BDD reviewer

on:
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - master
      - v*.*
  push:
    branches:
      - master
      - v*.*

jobs:
  assign_reviewer:
    runs-on: ubuntu-22.04
    steps:
      - name: Assign BDD reviewer
        uses: shufo/auto-assign-reviewer-by-files@v1.2.1
        with:
          config: ".github/assign_by_path.yml"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
```

assign_by_path.yml:

```
---
  "tests/e2e/**":
    - katyaaronov
  ".github/assign-by-path.yml":
    - katyaaronov
  ".github/labeler.yml":
    - katyaaronov
  ".github/workflows/assign_bdd_reviewer.yml":
    - katyaaronov
  ".github/workflows/bdd_assertthat_sync_from_github.yml":
    - katyaaronov
  ".github/workflows/bdd_get_tags.yml":
    - katyaaronov
  ".github/workflows/bdd_run_full_cycle*.yml":
    - katyaaronov
  ".github/workflows/bdd_run_label.yml":
    - katyaaronov
  ".github/workflows/bdd_run_ticket.yml":
    - katyaaronov
  ".github/workflows/bdd_validate.yml":
    - katyaaronov
  ".github/workflows/check-changes.yml":
    - katyaaronov

```
Thank you!

P.S. Is there a way to somehow pass all globs as an array instead of repeating the same reviewer for each?

**Comment by shufo** [comment]
Thanks for creating the issue.

I think the error cause is this action intended to use for feature branch not for default branch.


```yaml
  push:
    branches:
      - master
```

Currently pass all globs as an array is not supported but you can use glob for file names

```yaml
".github/workflows/*.yml":
  - ~~~
```
